### PR TITLE
Explicitly check if the connection of the table engine is the sql ser…

### LINKED ISSUE #450: After 4.2.8 I have this error: NoMethodError - undefined method `database_prefix_remote_server?'
```
NoMethodError - undefined method `database_prefix_remote_server?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f1ef003ee20>:
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:77:in `visit_Arel_Table'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:601:in `visit_Arel_Nodes_InnerJoin'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:794:in `block in inject_join'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:792:in `inject_join'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:96:in `visit_Arel_Nodes_JoinSource'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:248:in `visit_Arel_Nodes_SelectCore'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:67:in `block in visit_Arel_Nodes_SelectStatement'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:66:in `visit_Arel_Nodes_SelectStatement'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/reduce.rb:7:in `accept'
```

### PR DESCRIPTION
**Pull request by jippeholwerda**
…ver adapter. Fixes #450.

### CODE REVIEW

File: lib/arel/visitors/sqlserver.rb [hunk 1]
```diff
@@ -74,7 +74,10 @@ def visit_Arel_Nodes_SelectStatement o, collector
       end
 
       def visit_Arel_Table o, collector
-        table_name = if o.engine.connection.database_prefix_remote_server?
+        # Apparently, o.engine.connection can actually be a different adapter
+        # than sqlserver. Can be removed if fixed in ActiveRecord. See:
+        # github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/450
+        table_name = if o.engine.connection.respond_to?(:sqlserver?) and o.engine.connection.database_prefix_remote_server?
```
Comment (metaskills) [inline lib/arel/visitors/sqlserver.rb]: Thanks for this! I will be changing this to && unless there was a reason to use the lower version?
